name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
    
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Run linter
        needs: build
        run: npm run ci:lint

      - name: Type check
        needs: build
        run: npm run type-check

      -name: Run security audit
        needs: build
        run: npm audit

  tests: 
    runs-on: ubuntu-latest

      - name: Run e2e tests
        needs: build
        run: npm run test:e2e